name: Build and Test Node.js Project

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18] 
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Optional: Cache für npm-Abhängigkeiten, um Build-Zeiten zu reduzieren

      - name: Install dependencies
        run: npm install  # Oder `yarn install`, je nach deinem Projekt

      - name: Run Tests
        run: npm test  # Oder `yarn test`, je nach deinem Projekt

      - name: Build Project
        run: npm run build  # Oder `yarn build`, falls du ein Build-Skript definiert hast
